// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: data_interface.proto

package main

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Wavinfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Wavlist []*WavinfoWav `protobuf:"bytes,1,rep,name=wavlist,proto3" json:"wavlist,omitempty"`
}

func (x *Wavinfo) Reset() {
	*x = Wavinfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_interface_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Wavinfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wavinfo) ProtoMessage() {}

func (x *Wavinfo) ProtoReflect() protoreflect.Message {
	mi := &file_data_interface_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wavinfo.ProtoReflect.Descriptor instead.
func (*Wavinfo) Descriptor() ([]byte, []int) {
	return file_data_interface_proto_rawDescGZIP(), []int{0}
}

func (x *Wavinfo) GetWavlist() []*WavinfoWav {
	if x != nil {
		return x.Wavlist
	}
	return nil
}

type Fpiout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Wavlist []*FpioutFpi `protobuf:"bytes,1,rep,name=wavlist,proto3" json:"wavlist,omitempty"`
}

func (x *Fpiout) Reset() {
	*x = Fpiout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_interface_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fpiout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fpiout) ProtoMessage() {}

func (x *Fpiout) ProtoReflect() protoreflect.Message {
	mi := &file_data_interface_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fpiout.ProtoReflect.Descriptor instead.
func (*Fpiout) Descriptor() ([]byte, []int) {
	return file_data_interface_proto_rawDescGZIP(), []int{1}
}

func (x *Fpiout) GetWavlist() []*FpioutFpi {
	if x != nil {
		return x.Wavlist
	}
	return nil
}

type WavinfoWav struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msgtime int32   `protobuf:"varint,1,opt,name=msgtime,proto3" json:"msgtime,omitempty"`
	Number  int32   `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Wavlen  float32 `protobuf:"fixed32,3,opt,name=wavlen,proto3" json:"wavlen,omitempty"`
	Info    string  `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *WavinfoWav) Reset() {
	*x = WavinfoWav{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_interface_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WavinfoWav) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WavinfoWav) ProtoMessage() {}

func (x *WavinfoWav) ProtoReflect() protoreflect.Message {
	mi := &file_data_interface_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WavinfoWav.ProtoReflect.Descriptor instead.
func (*WavinfoWav) Descriptor() ([]byte, []int) {
	return file_data_interface_proto_rawDescGZIP(), []int{0, 0}
}

func (x *WavinfoWav) GetMsgtime() int32 {
	if x != nil {
		return x.Msgtime
	}
	return 0
}

func (x *WavinfoWav) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *WavinfoWav) GetWavlen() float32 {
	if x != nil {
		return x.Wavlen
	}
	return 0
}

func (x *WavinfoWav) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

type FpioutFpi struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msgtime int32   `protobuf:"varint,1,opt,name=msgtime,proto3" json:"msgtime,omitempty"`
	Number  int32   `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Wavlen  float32 `protobuf:"fixed32,3,opt,name=wavlen,proto3" json:"wavlen,omitempty"`
	Info    string  `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *FpioutFpi) Reset() {
	*x = FpioutFpi{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_interface_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FpioutFpi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FpioutFpi) ProtoMessage() {}

func (x *FpioutFpi) ProtoReflect() protoreflect.Message {
	mi := &file_data_interface_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FpioutFpi.ProtoReflect.Descriptor instead.
func (*FpioutFpi) Descriptor() ([]byte, []int) {
	return file_data_interface_proto_rawDescGZIP(), []int{1, 0}
}

func (x *FpioutFpi) GetMsgtime() int32 {
	if x != nil {
		return x.Msgtime
	}
	return 0
}

func (x *FpioutFpi) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *FpioutFpi) GetWavlen() float32 {
	if x != nil {
		return x.Wavlen
	}
	return 0
}

func (x *FpioutFpi) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

var File_data_interface_proto protoreflect.FileDescriptor

var file_data_interface_proto_rawDesc = []byte{
	0x0a, 0x14, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x22, 0xa5, 0x01, 0x0a, 0x07, 0x77, 0x61, 0x76, 0x69, 0x6e,
	0x66, 0x6f, 0x12, 0x35, 0x0a, 0x07, 0x77, 0x61, 0x76, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x66, 0x61, 0x63, 0x65, 0x2e, 0x77, 0x61, 0x76, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x77, 0x61, 0x76,
	0x52, 0x07, 0x77, 0x61, 0x76, 0x6c, 0x69, 0x73, 0x74, 0x1a, 0x63, 0x0a, 0x03, 0x77, 0x61, 0x76,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x73, 0x67, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x61, 0x76, 0x6c, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x06, 0x77, 0x61, 0x76, 0x6c, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0xa3,
	0x01, 0x0a, 0x06, 0x66, 0x70, 0x69, 0x6f, 0x75, 0x74, 0x12, 0x34, 0x0a, 0x07, 0x77, 0x61, 0x76,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x66, 0x70, 0x69, 0x6f,
	0x75, 0x74, 0x2e, 0x66, 0x70, 0x69, 0x52, 0x07, 0x77, 0x61, 0x76, 0x6c, 0x69, 0x73, 0x74, 0x1a,
	0x63, 0x0a, 0x03, 0x66, 0x70, 0x69, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x73, 0x67, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x74, 0x69, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x61, 0x76, 0x6c,
	0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x77, 0x61, 0x76, 0x6c, 0x65, 0x6e,
	0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x69, 0x6e, 0x66, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_data_interface_proto_rawDescOnce sync.Once
	file_data_interface_proto_rawDescData = file_data_interface_proto_rawDesc
)

func file_data_interface_proto_rawDescGZIP() []byte {
	file_data_interface_proto_rawDescOnce.Do(func() {
		file_data_interface_proto_rawDescData = protoimpl.X.CompressGZIP(file_data_interface_proto_rawDescData)
	})
	return file_data_interface_proto_rawDescData
}

var file_data_interface_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_data_interface_proto_goTypes = []interface{}{
	(*Wavinfo)(nil),    // 0: data_interface.wavinfo
	(*Fpiout)(nil),     // 1: data_interface.fpiout
	(*WavinfoWav)(nil), // 2: data_interface.wavinfo.wav
	(*FpioutFpi)(nil),  // 3: data_interface.fpiout.fpi
}
var file_data_interface_proto_depIdxs = []int32{
	2, // 0: data_interface.wavinfo.wavlist:type_name -> data_interface.wavinfo.wav
	3, // 1: data_interface.fpiout.wavlist:type_name -> data_interface.fpiout.fpi
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_data_interface_proto_init() }
func file_data_interface_proto_init() {
	if File_data_interface_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_data_interface_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Wavinfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_interface_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fpiout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_interface_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WavinfoWav); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_interface_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FpioutFpi); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_data_interface_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_data_interface_proto_goTypes,
		DependencyIndexes: file_data_interface_proto_depIdxs,
		MessageInfos:      file_data_interface_proto_msgTypes,
	}.Build()
	File_data_interface_proto = out.File
	file_data_interface_proto_rawDesc = nil
	file_data_interface_proto_goTypes = nil
	file_data_interface_proto_depIdxs = nil
}
