package main

import (
	"encoding/json"
	"encoding/xml"
	"fmt"
	"gopkg.in/yaml.v2"
	"log"
	"os"
)

func praseyaml() {
	data, err := os.ReadFile("companies.yaml")
	if err != nil {
		log.Println(err)
	}
	res := &AutoGenerated{}
	err = yaml.Unmarshal(data, res)
	if err != nil {
		log.Println(err)
	}
	for i, v := range res.ScrapeConfigs {
		fmt.Println(i, v)
	}
	b, _ := json.MarshalIndent(res.ScrapeConfigs, "", " ")
	os.WriteFile("companies.json", b, os.ModePerm)
	fmt.Println(res.ScrapeConfigs[2].StaticConfigs[0].Targets[0])
}
func prasejson() {
	data, err := os.ReadFile("config.json")
	if err != nil {
		log.Println(err)
	}
	res := &AutoGenerated{}
	err = json.Unmarshal(data, res)
	if err != nil {
		log.Println(err)
	}
	for i, v := range res.ScrapeConfigs {
		fmt.Println(i, v)
	}
}

func prasexml() {
	data, err := os.ReadFile("config.xml")
	if err != nil {
		log.Println(err)
	}
	res := &Servers{}
	xml.Unmarshal(data, res)
	for i, v := range res.Server {
		fmt.Println(i, v)
	}

}

func main() {
	prasejson()
	praseyaml()
	prasexml()
}
